### ISSUE TITLE
Bug: Build issues: (i) failure on Java 17, (ii) issue w/ some `settings.xml`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/pyrophen#3] opened 2022-02-10 20:29 UTC
## Description
I cloned the project and tried to build via `mvn package`, but I get an error that appears to be related to how my `~/.m2/settings.xml` is set up. @[ShahimEssaid](https://github.com/ShahimEssaid) helped me fix that error, but now I'm getting an error when trying to build w/ Java 17 (docs say that 11+ is supported).

## Sub-issue checklist
- [x] 1. Java 17 incompatibility
- [ ] 2. Incompatibility w/ certain `settings.xml` setups

### Errors
`[ERROR] Failed to execute goal org.springframework.experimental:spring-aot-maven-plugin:0.9.1:test-generate (test-generate) on project hpo-fhir-terminology: Build failed during Spring AOT test code generation: Unsupported class file major version 61 -> [Help 1]`

Log:
```
mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< org.hpo.fhir:hpo-fhir-terminology >------------------
[INFO] Building hpo-fhir-terminology 0.0.3
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ hpo-fhir-terminology ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hpo-fhir-terminology ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ hpo-fhir-terminology ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ hpo-fhir-terminology ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- spring-aot-maven-plugin:0.9.1:test-generate (test-generate) @ hpo-fhir-terminology ---
[INFO] Spring Native operating mode: native
[ERROR] java.lang.IllegalArgumentException: Unsupported class file major version 61
[ERROR] [sbg.asm.ClassReader.<init>(ClassReader.java:189), sbg.asm.ClassReader.<init>(ClassReader.java:170), sbg.asm.ClassReader.<init>(ClassReader.java:156), org.springframework.nativex.type.TypeSystem.findType(TypeSystem.java:251), org.springframework.nativex.type.TypeSystem.resolveSlashed(TypeSystem.java:196), org.springframework.nativex.type.TypeSystem.resolveSlashed(TypeSystem.java:181), org.springframework.nativex.type.TypeSystem.resolveDotted(TypeSystem.java:151), org.springframework.nativex.type.TypeSystem.resolveDotted(TypeSystem.java:160), org.springframework.nativex.type.TypeSystem.resolveName(TypeSystem.java:155), org.springframework.nativex.type.Type.unpackTypeHint(Type.java:1820), org.springframework.nativex.type.Type.lambda$unpackNativeHint$21(Type.java:1707), org.springframework.nativex.type.Type.processHintList(Type.java:1737), org.springframework.nativex.type.Type.unpackNativeHint(Type.java:1707), org.springframework.nativex.type.Type.unpackNativeHints(Type.java:2075), org.springframework.nativex.type.Type.unpackHints(Type.java:1653), org.springframework.nativex.type.Type.getCompilationHints(Type.java:2099), org.springframework.nativex.type.SpringConfiguration.<init>(SpringConfiguration.java:58), org.springframework.nativex.type.TypeSystem.ensureSpringConfigurationDiscovered(TypeSystem.java:662), org.springframework.nativex.type.TypeSystem.getAccessCheckers(TypeSystem.java:1047), org.springframework.nativex.support.ReflectionHandler.addAccess(ReflectionHandler.java:135), org.springframework.nativex.support.ReflectionHandler.addAccess(ReflectionHandler.java:91), org.springframework.nativex.support.ReflectionHandler.register(ReflectionHandler.java:73), org.springframework.nativex.support.SpringAnalyzer.analyze(SpringAnalyzer.java:76), org.springframework.aot.nativex.ConfigurationContributor.contribute(ConfigurationContributor.java:51), org.springframework.aot.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:74), org.springframework.aot.maven.TestGenerateMojo.execute(TestGenerateMojo.java:65), org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81), org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56), org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192), org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105), org.apache.maven.cli.MavenCli.execute(MavenCli.java:972), org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293), org.apache.maven.cli.MavenCli.main(MavenCli.java:196), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:568), org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282), org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225), org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406), org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.608 s
[INFO] Finished at: 2022-02-10T18:06:59-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.experimental:spring-aot-maven-plugin:0.9.1:test-generate (test-generate) on project hpo-fhir-terminology: Build failed during Spring AOT test code generation: Unsupported class file major version 61 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### Causes
The cause was because I was running Java 17.

We determined this by looking at class numbers: https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers
> Java 11 uses major version 55
> Java 17 uses major version 61

After I installed and set Java 11 as my `JAVA_HOME` for the project, I got:
`[INFO] BUILD SUCCESS` :D

### Possible solutions
As far as I can tell, the options are:
a. Update so that the project is compatible Java versions higher than 11.
b. Update the documentation to specifically require Java 11.

## Issue 2: `settings.xml`
I have an `~/.m2/settings.xml` that was causing problems for the build process, until I commented out the `mirror` section.

### Errors
`[ERROR] Plugin org.springframework.experimental:spring-aot-maven-plugin:0.9.1 or one of its dependencies could not be resolved: Could not find artifact org.springframework.experimental:spring-aot-maven-plugin:jar:0.9.1 in informatics (https://nexus.informatics.com/repository/komet/) -> [Help 1]`

Here's the full log:
```
mvn package
[INFO] Scanning for projects...
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/boot/spring-boot-starter-parent/2.4.4/spring-boot-starter-parent-2.4.4.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/springframework/boot/spring-boot-starter-parent/2.4.4/spring-boot-starter-parent-2.4.4.pom (8.6 kB at 4.3 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/boot/spring-boot-dependencies/2.4.4/spring-boot-dependencies-2.4.4.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/springframework/boot/spring-boot-dependencies/2.4.4/spring-boot-dependencies-2.4.4.pom (108 kB at 101 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/com/datastax/oss/java-driver-bom/4.9.0/java-driver-bom-4.9.0.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/com/datastax/oss/java-driver-bom/4.9.0/java-driver-bom-4.9.0.pom (4.1 kB at 6.3 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/io/dropwizard/metrics/metrics-bom/4.1.18/metrics-bom-4.1.18.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/io/dropwizard/metrics/metrics-bom/4.1.18/metrics-bom-4.1.18.pom (5.3 kB at 8.3 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/io/dropwizard/metrics/metrics-parent/4.1.18/metrics-parent-4.1.18.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/io/dropwizard/metrics/metrics-parent/4.1.18/metrics-parent-4.1.18.pom (17 kB at 22 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/codehaus/groovy/groovy-bom/2.5.14/groovy-bom-2.5.14.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/codehaus/groovy/groovy-bom/2.5.14/groovy-bom-2.5.14.pom (26 kB at 36 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/infinispan/infinispan-bom/11.0.10.Final/infinispan-bom-11.0.10.Final.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/infinispan/infinispan-bom/11.0.10.Final/infinispan-bom-11.0.10.Final.pom (19 kB at 29 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/infinispan/infinispan-build-configuration-parent/11.0.10.Final/infinispan-build-configuration-parent-11.0.10.Final.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/infinispan/infinispan-build-configuration-parent/11.0.10.Final/infinispan-build-configuration-parent-11.0.10.Final.pom (13 kB at 22 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/jboss/jboss-parent/36/jboss-parent-36.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/jboss/jboss-parent/36/jboss-parent-36.pom (66 kB at 86 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/com/fasterxml/jackson/jackson-bom/2.11.4/jackson-bom-2.11.4.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/com/fasterxml/jackson/jackson-bom/2.11.4/jackson-bom-2.11.4.pom (0 B at 0 B/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/com/fasterxml/jackson/jackson-parent/2.11/jackson-parent-2.11.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/com/fasterxml/jackson/jackson-parent/2.11/jackson-parent-2.11.pom (0 B at 0 B/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/glassfish/jersey/jersey-bom/2.32/jersey-bom-2.32.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/glassfish/jersey/jersey-bom/2.32/jersey-bom-2.32.pom (19 kB at 30 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/eclipse/jetty/jetty-bom/9.4.38.v20210224/jetty-bom-9.4.38.v20210224.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/eclipse/jetty/jetty-bom/9.4.38.v20210224/jetty-bom-9.4.38.v20210224.pom (18 kB at 27 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/jetbrains/kotlin/kotlin-bom/1.4.31/kotlin-bom-1.4.31.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/jetbrains/kotlin/kotlin-bom/1.4.31/kotlin-bom-1.4.31.pom (9.3 kB at 15 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/apache/logging/log4j/log4j-bom/2.13.3/log4j-bom-2.13.3.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/apache/logging/log4j/log4j-bom/2.13.3/log4j-bom-2.13.3.pom (7.6 kB at 8.5 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/io/micrometer/micrometer-bom/1.6.5/micrometer-bom-1.6.5.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/io/micrometer/micrometer-bom/1.6.5/micrometer-bom-1.6.5.pom (6.8 kB at 8.2 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/io/netty/netty-bom/4.1.60.Final/netty-bom-4.1.60.Final.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/io/netty/netty-bom/4.1.60.Final/netty-bom-4.1.60.Final.pom (8.8 kB at 11 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/com/oracle/database/jdbc/ojdbc-bom/19.8.0.0/ojdbc-bom-19.8.0.0.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/com/oracle/database/jdbc/ojdbc-bom/19.8.0.0/ojdbc-bom-19.8.0.0.pom (12 kB at 18 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/io/r2dbc/r2dbc-bom/Arabba-SR9/r2dbc-bom-Arabba-SR9.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/io/r2dbc/r2dbc-bom/Arabba-SR9/r2dbc-bom-Arabba-SR9.pom (4.1 kB at 6.3 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/io/projectreactor/reactor-bom/2020.0.5/reactor-bom-2020.0.5.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/io/projectreactor/reactor-bom/2020.0.5/reactor-bom-2020.0.5.pom (4.5 kB at 7.4 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/io/rsocket/rsocket-bom/1.1.0/rsocket-bom-1.1.0.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/io/rsocket/rsocket-bom/1.1.0/rsocket-bom-1.1.0.pom (2.6 kB at 4.4 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/data/spring-data-bom/2020.0.6/spring-data-bom-2020.0.6.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/springframework/data/spring-data-bom/2020.0.6/spring-data-bom-2020.0.6.pom (5.9 kB at 9.5 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/spring-framework-bom/5.3.5/spring-framework-bom-5.3.5.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/springframework/spring-framework-bom/5.3.5/spring-framework-bom-5.3.5.pom (5.6 kB at 9.2 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/integration/spring-integration-bom/5.4.5/spring-integration-bom-5.4.5.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/springframework/integration/spring-integration-bom/5.4.5/spring-integration-bom-5.4.5.pom (9.5 kB at 15 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/security/spring-security-bom/5.4.5/spring-security-bom-5.4.5.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/springframework/security/spring-security-bom/5.4.5/spring-security-bom-5.4.5.pom (5.3 kB at 8.2 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/session/spring-session-bom/2020.0.3/spring-session-bom-2020.0.3.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/springframework/session/spring-session-bom/2020.0.3/spring-session-bom-2020.0.3.pom (2.7 kB at 4.0 kB/s)
[INFO]
[INFO] -----------------< org.hpo.fhir:hpo-fhir-terminology >------------------
[INFO] Building hpo-fhir-terminology 0.0.3
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/boot/spring-boot-maven-plugin/2.4.4/spring-boot-maven-plugin-2.4.4.pom
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/springframework/boot/spring-boot-maven-plugin/2.4.4/spring-boot-maven-plugin-2.4.4.pom (2.9 kB at 4.7 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/boot/spring-boot-maven-plugin/2.4.4/spring-boot-maven-plugin-2.4.4.jar
Downloaded from informatics: https://nexus.informatics.com/repository/komet/org/springframework/boot/spring-boot-maven-plugin/2.4.4/spring-boot-maven-plugin-2.4.4.jar (101 kB at 147 kB/s)
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/experimental/spring-aot-maven-plugin/0.9.1/spring-aot-maven-plugin-0.9.1.pom
[WARNING] The POM for org.springframework.experimental:spring-aot-maven-plugin:jar:0.9.1 is missing, no dependency information available
Downloading from informatics: https://nexus.informatics.com/repository/komet/org/springframework/experimental/spring-aot-maven-plugin/0.9.1/spring-aot-maven-plugin-0.9.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.248 s
[INFO] Finished at: 2022-02-10T15:24:15-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.springframework.experimental:spring-aot-maven-plugin:0.9.1 or one of its dependencies could not be resolved: Could not find artifact org.springframework.experimental:spring-aot-maven-plugin:jar:0.9.1 in informatics (https://nexus.informatics.com/repository/komet/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

```

### Additional information
I am not the best at Java. I'm surprised that it's trying to pull from the 'komet' repository. It's in my `settings.xml`, but why are repositories in my `settings.xml` being used instead of what's defined in the Pyrophen `pom.xml`?

`~/.m2/settings.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd"
          xmlns="http://maven.apache.org/SETTINGS/1.1.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <offline>false</offline>
    <mirrors>
        <mirror>
            <!--This sends everything else to /public -->
            <id>informatics</id>
            <mirrorOf>*</mirrorOf>
            <url>https://nexus.informatics.com/repository/komet/</url>
        </mirror>
    </mirrors>
    <servers>
        <server>
            <username>jflack</username>
            <password>REDACTED</password>
            <id>informatics</id>
        </server>
        <server>
            <username>jflack</username>
            <password>REDACTED</password>
            <id>snapshots</id>
        </server>
     </servers>
    <profiles>
         <profile>
            <repositories>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>informatics</id>
                    <name>libs-release</name>
                    <url>https://nexus.informatics.com/repository/komet/</url>
                </repository>
                <repository>
                    <snapshots />
                    <id>snapshots</id>
                    <name>libs-snapshot</name>
                    <url>https://nexus.informatics.com/repository/komet-snapshot/</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>informatics</id>
                    <name>plugins-release</name>
                    <url>https://nexus.informatics.com/repository/komet/</url>
                </pluginRepository>
                <pluginRepository>
                    <snapshots />
                    <id>snapshots</id>
                    <name>plugins-snapshot</name>
                    <url>https://nexus.informatics.com/repository/komet-snapshot/</url>
                </pluginRepository>
            </pluginRepositories>
            <id>nexus</id>
        </profile>
        <profile>
            <id>release-deploy</id>
            <properties>
                <altDeploymentRepository>informatics::default::https://nexus.informatics.com/repository/komet-release/</altDeploymentRepository>
            </properties>
        </profile>
        <profile>
            <id>snapshot-deploy</id>
            <properties>
                <altDeploymentRepository>informatics::default::https://nexus.informatics.com/repository/komet-snapshot/</altDeploymentRepository>
            </properties>
        </profile>
        <profile>
            <id>plugins</id>
            <properties>
                <plugins>true</plugins>
            </properties>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>snapshot-deploy</activeProfile>
        <activeProfile>nexus</activeProfile>
    </activeProfiles>

</settings>
```

I see that `pom.xml` appears to have what is needed, but I suppose it seems to be overridden by the `settings.xml`. We also tried adding the maven central repository to it, but that didn't help:

```xml
    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
        <repository>
            <id>spring-releases</id>
            <name>Spring Releases</name>
            <url>https://repo.spring.io/release</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-releases</id>
            <name>Spring Releases</name>
            <url>https://repo.spring.io/release</url>
        </pluginRepository>
    </pluginRepositories>
```

One article I read (Shahim agreed) even said that it is not a good practice to put `repositories` or `pluginRepositories` in `pom.xml`: https://blog.sonatype.com/2009/02/why-putting-repositories-in-your-poms-is-a-bad-idea/

### Solution
We commented out the following in `settings.xml`, which fixed the problem:
```xml
        <mirror>
            <id>informatics</id>
            <mirrorOf>*</mirrorOf>
            <url>https://nexus.informatics.com/repository/komet/</url>
        </mirror>
```

However, I've decided to leave this open, because I am wondering if there is some way to work around whatever `settings.xml` someone has set up. I could be wrong though, in which case I should consider this problem solved.

**Comment by pnrobinson** [comment] 2022-02-10 22:14
@joeflack4 my best guess is that at some point you added non-standard repositories to the settings.xml file and that the non-standard repositories do not have the required resources. By default, the settings.xml file does not have links to repositories. 
One thing that might helkp to determine if this is the cause of this problem would be to comment out the repositories part of your settings.xml file and then do a mvn clean package in the pyrophen repo. 
Here is a good explanation of what the settings.xml file is good for  https://www.baeldung.com/maven-settings-xml

**Comment by joeflack4** [comment] 2022-02-10 22:19
@pnrobinson Yeah, I'm just finding out about that. Shahim had me comment out that stuff and we were able to get past this issue. I'm in the middle of updating the issue right now w/ the next error I got.

**Comment by joeflack4** [comment] 2022-02-10 23:12
@pnrobinson I've updated the issue w/ the main problem I'm having. See: "Issue 1: Java 17" above.

I also added additional details / thoughts to "Issue 2: settings.xml".

**Comment by pnrobinson** [comment] 2022-02-10 23:30
I can confirm I get the same error when trying to build with Java 17 (Build failed during Spring AOT test code generation: Unsupported class file major version 61 ).

**Comment by pnrobinson** [comment] 2022-02-10 23:43
@joeflack4  I adjusted the pom file, there was an older plugin that actually was not even necessary that seemed to be causing the problem. The application runs now on my machine (linux, Java 17). Please let me know if this fixes things on your side!

**Comment by joeflack4** [comment] 2022-02-11 00:51
@pnrobinson 

<img width="874" alt="Screen Shot 2022-02-10 at 7 52 18 PM" src="https://user-images.githubusercontent.com/13045020/153521572-e2d89625-6e48-482a-81f4-ac894bd99468.png">


```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ hpo-fhir-terminology ---
[INFO] Building jar: /Users/joeflack4/projects/pyrophen/target/pyrophen.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:2.4.4:repackage (repackage) @ hpo-fhir-terminology ---
[INFO] Replacing main artifact with repackaged archive
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

I marked "issue 1" as complete. Do you want me to split the issue into 2 and close one of them? Or just close both, assuming it's not possible to fix the `settings.xml` issue on the project side, rather than on the user side?

**Comment by pnrobinson** [comment] 2022-02-11 12:38
Borat was pure genius! Love it!
To the best of my knowledge, the settings.xml issue can only be fixed on your side so I will close this issue! But I'd be glad to participate in the project at any stage where I could be helpful.

**Closed as completed by pnrobinson** 2022-02-11 12:38 UTC
